"""Locate official KiCad footprints and pick one for a mounting hole."""

from __future__ import annotations

import os
import re
import urllib.request
from functools import lru_cache
from pathlib import Path

from . import sexpr
from .schema import Hole
from .sexpr import Sym

# kicad-footprints git ref used when no local KiCad library is installed.
FOOTPRINT_REF = os.environ.get("KICRATE_FOOTPRINT_REF", "master")
_RAW = "https://gitlab.com/kicad/libraries/kicad-footprints/-/raw/{ref}/{lib}.pretty/{name}.kicad_mod"
_TREE = "https://gitlab.com/api/v4/projects/kicad%2Flibraries%2Fkicad-footprints/repository/tree?path={lib}.pretty&ref={ref}&per_page=100&page={page}"

_CANDIDATE_DIRS = [
    "/usr/share/kicad/footprints",
    "/usr/local/share/kicad/footprints",
    "/Applications/KiCad/KiCad.app/Contents/SharedSupport/footprints",
    r"C:\Program Files\KiCad\10.0\share\kicad\footprints",
]


def library_dir() -> Path | None:
    for var in ("KICRATE_FOOTPRINT_DIR", "KICAD10_FOOTPRINT_DIR"):
        if os.environ.get(var):
            return Path(os.environ[var])
    for d in _CANDIDATE_DIRS:
        if Path(d, "MountingHole.pretty").is_dir():
            return Path(d)
    return None


def _cache_dir() -> Path:
    d = Path(os.environ.get("KICRATE_CACHE", Path.home() / ".cache" / "kicrate")) / "footprints" / FOOTPRINT_REF
    d.mkdir(parents=True, exist_ok=True)
    return d


@lru_cache
def list_footprints(lib: str) -> frozenset[str]:
    local = library_dir()
    if local:
        return frozenset(p.stem for p in (local / f"{lib}.pretty").glob("*.kicad_mod"))
    cache = _cache_dir() / f"{lib}.index"
    if not cache.exists():
        import json

        names, page = [], 1
        while True:
            with urllib.request.urlopen(_TREE.format(lib=lib, ref=FOOTPRINT_REF, page=page), timeout=30) as r:
                batch = json.load(r)
            names += [e["name"].removesuffix(".kicad_mod") for e in batch if e["name"].endswith(".kicad_mod")]
            if len(batch) < 100:
                break
            page += 1
        cache.write_text("\n".join(sorted(names)))
    return frozenset(cache.read_text().split())


@lru_cache
def load(lib_id: str) -> list:
    lib, name = lib_id.split(":", 1)
    local = library_dir()
    if local:
        text = (local / f"{lib}.pretty" / f"{name}.kicad_mod").read_text()
    else:
        cache = _cache_dir() / f"{lib}.pretty" / f"{name}.kicad_mod"
        if not cache.exists():
            cache.parent.mkdir(parents=True, exist_ok=True)
            with urllib.request.urlopen(_RAW.format(ref=FOOTPRINT_REF, lib=lib, name=name), timeout=30) as r:
                cache.write_bytes(r.read())
        text = cache.read_text()
    return sexpr.loads(text)


def _drill_str(d: float) -> str:
    return f"{d:g}"


def pick(hole: Hole) -> str:
    """Official footprint whose drill equals the hole exactly, else a generated one.

    Prefers the variant matching a metric screw (e.g. `_M3`) when the hole's
    screw names one. Returns a lib_id; ids starting with `KiCrate:` are
    generated by `generated_mounting_hole`.
    """
    if hole.footprint:
        return hole.footprint
    names = list_footprints("MountingHole")
    base = f"MountingHole_{_drill_str(hole.drill)}mm"
    suffix = "_Pad" if hole.plated else ""
    pattern = re.compile(rf"^{re.escape(base)}(_M[\d.]+)?{suffix}$")
    matches = sorted(n for n in names if pattern.match(n))
    if matches:
        m = re.search(r"\bM(\d+(?:\.\d+)?)\b", hole.screw or "")
        if m:
            for n in matches:
                if f"_M{m.group(1)}" in n:
                    return f"MountingHole:{n}"
        plain = f"{base}{suffix}"
        return f"MountingHole:{plain if plain in matches else matches[0]}"
    return f"KiCrate:{base}{suffix}"


def generated_mounting_hole(lib_id: str, drill: float, plated: bool) -> list:
    """Footprint in the same shape as KiCad's generated MountingHole_* parts."""
    name = lib_id.split(":", 1)[1]
    r = drill / 2
    pad_d = drill * 2 if plated else drill

    def prop(key, val, y, layer, hide=False):
        node = [Sym("property"), key, val, [Sym("at"), 0, y, 0], [Sym("layer"), layer]]
        if hide:
            node.append([Sym("hide"), Sym("yes")])
        node.append([Sym("effects"), [Sym("font"), [Sym("size"), 1, 1], [Sym("thickness"), 0.15]]])
        return node

    crt = max(pad_d / 2, r) + 0.25
    fp = [
        Sym("footprint"),
        name,
        [Sym("layer"), "F.Cu"],
        [Sym("descr"), f"Mounting Hole {drill:g}mm (generated by KiCrate: no matching official footprint)"],
        [Sym("tags"), "mountinghole"],
        prop("Reference", "REF**", -(crt + 0.7), "F.SilkS"),
        prop("Value", name, crt + 0.7, "F.Fab"),
        [Sym("attr"), Sym("exclude_from_pos_files"), Sym("exclude_from_bom")],
        [Sym("fp_circle"), [Sym("center"), 0, 0], [Sym("end"), max(pad_d / 2, r), 0],
         [Sym("stroke"), [Sym("width"), 0.15], [Sym("type"), Sym("solid")]], [Sym("fill"), Sym("no")], [Sym("layer"), "Cmts.User"]],
        [Sym("fp_circle"), [Sym("center"), 0, 0], [Sym("end"), crt, 0],
         [Sym("stroke"), [Sym("width"), 0.05], [Sym("type"), Sym("solid")]], [Sym("fill"), Sym("no")], [Sym("layer"), "F.CrtYd"]],
    ]
    if plated:
        fp.append([Sym("pad"), "1", Sym("thru_hole"), Sym("circle"), [Sym("at"), 0, 0], [Sym("size"), pad_d, pad_d],
                   [Sym("drill"), drill], [Sym("layers"), "*.Cu", "*.Mask"]])
    else:
        fp.append([Sym("pad"), "", Sym("np_thru_hole"), Sym("circle"), [Sym("at"), 0, 0], [Sym("size"), drill, drill],
                   [Sym("drill"), drill], [Sym("layers"), "*.Cu", "*.Mask"]])
    return fp


def footprint_for(hole: Hole) -> tuple[str, list]:
    lib_id = pick(hole)
    if lib_id.startswith("KiCrate:"):
        return lib_id, generated_mounting_hole(lib_id, hole.drill, hole.plated)
    return lib_id, load(lib_id)
